version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db_embeleza
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_embeleza
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: api-embeleza
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - db

volumes:
  pgdata:
    driver: local